version: '3'

services:
  web:
    container_name: "django-base-web"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    command: >
      sh -c "python3 manage.py migrate &&
        python3 manage.py wait_for_db &&
        python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: "django-base-db"
    image: postgres:10-alpine
    env_file:
      - ./.env
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  redis:
    container_name: "django-base-redis"
    image: redis:alpine

  celery:
    container_name: "django-base-celery"
    restart: always
    build: .
    command: celery -A project worker --loglevel=info --purge
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres-data: